import React from "react"

import { Card } from "~/components/card"
import { Item } from "~/lib/items"
import { clsx } from "~/lib/utils"

export interface GalleryProps {
  className?: string
  items: Item[]
  columns?: 1 | 2 | 3 | 4
}

export function Gallery({ className, items, columns = 3 }: GalleryProps) {
  if (items.length === 0) {
    return null
  }

  if (items.length === 1) {
    const first = items[0]
    if (first?.type === "image") {
      return (
        <div className={clsx(className, "grid grid-cols-1 gap-4")}>
          <Card
            key={first.src}
            aspectRatio="portrait"
            className="col-span-1"
            href={first.href}
            title={first.title}
            description={first.description}
            preview={
              <img
                alt={first.title}
                className="rounded-xl object-cover"
                src={first.thumb ? first.thumb : first.src}
              />
            }
            size="large"
          />
        </div>
      )
    }
  }

  return (
    <div
      className={clsx(
        className,
        "grid gap-4",
        columns === 1 && "grid-cols-1",
        columns === 2 && "grid-cols-2",
        columns === 3 && "grid-cols-3",
        columns === 4 && "grid-cols-4",
      )}
    >
      {items.map((item) => {
        if (item.type === "image") {
          return (
            <Card
              key={item.src}
              aspectRatio="portrait"
              href={item.href}
              title={item.title}
              description={item.description}
              preview={
                <img
                  alt={item.title}
                  className="rounded-xl object-cover"
                  src={item.thumb ? item.thumb : item.src}
                />
              }
            />
          )
        }
        return (
          <Card
            key={item.title}
            aspectRatio="portrait"
            href={item.href}
            title={item.title}
            description={item.description}
          />
        )
      })}
    </div>
  )
}
